dist: trusty
language: go
go:
  - "1.12"
env:
  - GO111MODULE=on
os:
  - linux
  - osx
install: &install
  - sudo apt-get update
  - sudo apt-get install -y libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev xsltproc
script:
  - make
  - make lint
  - make test
jobs:
  include:
    - stage: "bundle"
      install: *install
      script:
        - make release
      env:
        - GO111MODULE=on
stages:
  - "test"
  - "bundle"
