dist: trusty
language: go
go:
  - "1.12"
env:
  - GOOS=linux GOARCH=amd64
  - GOOS=darwin GOARCH=amd64
jobs:
  include:
    - stage: "build"
      name: "build"
      install:
        - sudo apt-get update
        - sudo apt-get install -y libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
      script:
        - make
        - make lint
        - make test
    - stage: "deploy"
      script: echo "todo"
stages:
  - "build"
  - "bundle"
  - name: "deploy"
    if: branch = master
env:
  global:
    - GO111MODULE=on
