dist: trusty
language: go
deploy:
  provider: s3
  skip_cleanup: true
  file:
    - ./dist/charlestown.tar.gz
  on:
    env:
      - GO111MODULE=on
      - GOOS=darwin
go:
  - "1.12"
env:
  - GOOS=linux GOARCH=amd64 GO111MODULE=on
  - GOOS=darwin GOARCH=amd64 GO111MODULE=on
install:
  - sudo apt-get update
  - sudo apt-get install -y libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
script:
  - make
  - make lint
  - make test
jobs:
  include:
    - stage: "bundle"
      install:
        - sudo apt-get update
        - sudo apt-get install -y libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
      script:
        - make tar
      env:
        - GO111MODULE=on
        - GOOS=darwin
stages:
  - "test"
  - "bundle"
