dist: trusty
language: go
go:
  - "1.12"
env:
  - GO111MODULE=on
os:
  - linux
  - osx
before_install: &before_install
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
install: &install
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libgl1-mesa-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libxcursor-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libxrandr-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libxinerama-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libxi-dev xsltproc; fi
script:
  - make
  - make lint
  - make test
  - make bundle
deploy: &deploy
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  file: ./dist/artifacts/*.tar.gz
  on:
    all_branches: true
jobs:
  include:
    - stage: "bundle"
      install: *install
      script: make osx
      deploy: *deploy
      os: osx
stages:
  - "test"
  - "bundle"
