dist: trusty
language: go
go:
  - "1.12"
env:
  - GOOS=linux GOARCH=amd64 GO111MODULE=on
  - GOOS=darwin GOARCH=amd64 GO111MODULE=on
install: &install
  - sudo apt-get update
  - sudo apt-get install -y libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev xsltproc
script:
  - make
  - make lint
  - make test
jobs:
  include:
    - stage: "bundle"
      install: *install
      script:
        - make release
      deploy:
        provider: s3
        skip_cleanup: true
        file: ./dist/artifacts/*.tar.gz
        on:
          all_branches: true
          condition: $GOOS == darwin
      env:
        - GO111MODULE=on
        - GOOS=darwin
stages:
  - "test"
  - "bundle"
