dist: trusty
language: go
addons:
  apt:
    packages:
      - libxcursor-dev
go:
  - "1.12"
jobs:
  include:
    - stage: "build"
      name: "build"
      script:
        - make
        - make lint
        - make test
    - stage: "deploy"
      script: echo "todo"
stages:
  - "build"
  - name: "deploy"
    if: branch = master
env:
  global:
    - GO111MODULE=on
