dist: trusty
language: go
addons:
  artifacts:
    debug: true
    paths:
      - ./dist/charlestown/bin/
go:
  - "1.12"
env:
  - GOOS=linux GOARCH=amd64 GO111MODULE=on
  - GOOS=darwin GOARCH=amd64 GO111MODULE=on
script:
  - sudo apt-get update
  - sudo apt-get install -y libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
  - make
  - make lint
  - make test
jobs:
  include:
    - stage: "bundle"
      script:
        - make tar
      env:
        - GOOS=darwin
stages:
  - "test"
  - "bundle"
